FROM alpine:latest

RUN apk add --no-cache git bash g++ linux-headers curl wget mc python3 py3-pip python3-dev rust cargo libffi-dev libressl-dev
RUN ln -s /usr/bin/python3 /usr/bin/python

RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install grpcio
RUN python3 -m pip install grpcio-tools
RUN python3 -m pip install sonora
RUN python3 -m pip install daphne

WORKDIR /app/backend
COPY ./proto ./proto

WORKDIR /app/backend/src

EXPOSE 8081
EXPOSE 9000

ENTRYPOINT ["/bin/bash"]